// Inline script that registers the Workbox-generated service worker on page
// load. Deliberately written as a string (not a module) because TanStack Start
// renders the document via React on both server and client, so we cannot rely
// on `virtual:pwa-register` resolving in the SSR build environment.
//
// The SW itself is generated by `vite-plugin-pwa` (see vite.config.ts) and
// uses `registerType: "autoUpdate"` → it includes skipWaiting + clientsClaim,
// so the next page load picks up new versions automatically.
export const SERVICE_WORKER_REGISTER_SCRIPT = `if('serviceWorker' in navigator){window.addEventListener('load',function(){navigator.serviceWorker.register('/sw.js').catch(function(){})});}`;
