/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SetlistsRouteRouteImport } from './routes/setlists/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SongsIndexRouteImport } from './routes/songs/index'
import { Route as SetlistsIndexRouteImport } from './routes/setlists/index'
import { Route as SetlistsIdRouteImport } from './routes/setlists/$id'
import { Route as SongsIdIndexRouteImport } from './routes/songs/$id/index'
import { Route as SongsIdPerformRouteImport } from './routes/songs/$id/perform'
import { Route as ApiAuthTestLoginRouteImport } from './routes/api/auth/test-login'
import { Route as ApiAuthGoogleRouteImport } from './routes/api/auth/google'
import { Route as ApiAuthCallbackRouteImport } from './routes/api/auth/callback'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SetlistsRouteRoute = SetlistsRouteRouteImport.update({
  id: '/setlists',
  path: '/setlists',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SongsIndexRoute = SongsIndexRouteImport.update({
  id: '/songs/',
  path: '/songs/',
  getParentRoute: () => rootRouteImport,
} as any)
const SetlistsIndexRoute = SetlistsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SetlistsRouteRoute,
} as any)
const SetlistsIdRoute = SetlistsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SetlistsRouteRoute,
} as any)
const SongsIdIndexRoute = SongsIdIndexRouteImport.update({
  id: '/songs/$id/',
  path: '/songs/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const SongsIdPerformRoute = SongsIdPerformRouteImport.update({
  id: '/songs/$id/perform',
  path: '/songs/$id/perform',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthTestLoginRoute = ApiAuthTestLoginRouteImport.update({
  id: '/api/auth/test-login',
  path: '/api/auth/test-login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthGoogleRoute = ApiAuthGoogleRouteImport.update({
  id: '/api/auth/google',
  path: '/api/auth/google',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthCallbackRoute = ApiAuthCallbackRouteImport.update({
  id: '/api/auth/callback',
  path: '/api/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/setlists': typeof SetlistsRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/setlists/$id': typeof SetlistsIdRoute
  '/setlists/': typeof SetlistsIndexRoute
  '/songs/': typeof SongsIndexRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/google': typeof ApiAuthGoogleRoute
  '/api/auth/test-login': typeof ApiAuthTestLoginRoute
  '/songs/$id/perform': typeof SongsIdPerformRoute
  '/songs/$id/': typeof SongsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/setlists/$id': typeof SetlistsIdRoute
  '/setlists': typeof SetlistsIndexRoute
  '/songs': typeof SongsIndexRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/google': typeof ApiAuthGoogleRoute
  '/api/auth/test-login': typeof ApiAuthTestLoginRoute
  '/songs/$id/perform': typeof SongsIdPerformRoute
  '/songs/$id': typeof SongsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/setlists': typeof SetlistsRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/setlists/$id': typeof SetlistsIdRoute
  '/setlists/': typeof SetlistsIndexRoute
  '/songs/': typeof SongsIndexRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/google': typeof ApiAuthGoogleRoute
  '/api/auth/test-login': typeof ApiAuthTestLoginRoute
  '/songs/$id/perform': typeof SongsIdPerformRoute
  '/songs/$id/': typeof SongsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/setlists'
    | '/login'
    | '/settings'
    | '/setlists/$id'
    | '/setlists/'
    | '/songs/'
    | '/api/auth/callback'
    | '/api/auth/google'
    | '/api/auth/test-login'
    | '/songs/$id/perform'
    | '/songs/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/settings'
    | '/setlists/$id'
    | '/setlists'
    | '/songs'
    | '/api/auth/callback'
    | '/api/auth/google'
    | '/api/auth/test-login'
    | '/songs/$id/perform'
    | '/songs/$id'
  id:
    | '__root__'
    | '/'
    | '/setlists'
    | '/login'
    | '/settings'
    | '/setlists/$id'
    | '/setlists/'
    | '/songs/'
    | '/api/auth/callback'
    | '/api/auth/google'
    | '/api/auth/test-login'
    | '/songs/$id/perform'
    | '/songs/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SetlistsRouteRoute: typeof SetlistsRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
  SongsIndexRoute: typeof SongsIndexRoute
  ApiAuthCallbackRoute: typeof ApiAuthCallbackRoute
  ApiAuthGoogleRoute: typeof ApiAuthGoogleRoute
  ApiAuthTestLoginRoute: typeof ApiAuthTestLoginRoute
  SongsIdPerformRoute: typeof SongsIdPerformRoute
  SongsIdIndexRoute: typeof SongsIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setlists': {
      id: '/setlists'
      path: '/setlists'
      fullPath: '/setlists'
      preLoaderRoute: typeof SetlistsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/songs/': {
      id: '/songs/'
      path: '/songs'
      fullPath: '/songs/'
      preLoaderRoute: typeof SongsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setlists/': {
      id: '/setlists/'
      path: '/'
      fullPath: '/setlists/'
      preLoaderRoute: typeof SetlistsIndexRouteImport
      parentRoute: typeof SetlistsRouteRoute
    }
    '/setlists/$id': {
      id: '/setlists/$id'
      path: '/$id'
      fullPath: '/setlists/$id'
      preLoaderRoute: typeof SetlistsIdRouteImport
      parentRoute: typeof SetlistsRouteRoute
    }
    '/songs/$id/': {
      id: '/songs/$id/'
      path: '/songs/$id'
      fullPath: '/songs/$id/'
      preLoaderRoute: typeof SongsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/songs/$id/perform': {
      id: '/songs/$id/perform'
      path: '/songs/$id/perform'
      fullPath: '/songs/$id/perform'
      preLoaderRoute: typeof SongsIdPerformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/test-login': {
      id: '/api/auth/test-login'
      path: '/api/auth/test-login'
      fullPath: '/api/auth/test-login'
      preLoaderRoute: typeof ApiAuthTestLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/google': {
      id: '/api/auth/google'
      path: '/api/auth/google'
      fullPath: '/api/auth/google'
      preLoaderRoute: typeof ApiAuthGoogleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/callback': {
      id: '/api/auth/callback'
      path: '/api/auth/callback'
      fullPath: '/api/auth/callback'
      preLoaderRoute: typeof ApiAuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SetlistsRouteRouteChildren {
  SetlistsIdRoute: typeof SetlistsIdRoute
  SetlistsIndexRoute: typeof SetlistsIndexRoute
}

const SetlistsRouteRouteChildren: SetlistsRouteRouteChildren = {
  SetlistsIdRoute: SetlistsIdRoute,
  SetlistsIndexRoute: SetlistsIndexRoute,
}

const SetlistsRouteRouteWithChildren = SetlistsRouteRoute._addFileChildren(
  SetlistsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SetlistsRouteRoute: SetlistsRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
  SongsIndexRoute: SongsIndexRoute,
  ApiAuthCallbackRoute: ApiAuthCallbackRoute,
  ApiAuthGoogleRoute: ApiAuthGoogleRoute,
  ApiAuthTestLoginRoute: ApiAuthTestLoginRoute,
  SongsIdPerformRoute: SongsIdPerformRoute,
  SongsIdIndexRoute: SongsIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
